In [1]:
import random
def get_score() -> list:
    score = []
    for i in range(5):
        score.append(random.randint(50, 100))
    return score

def get_names(nums:int) -> list:
    with open('names.txt',encoding='utf-8',newline='') as file:
        names_str = file.read()
        all_names_list = names_str.split(sep="\n")
        names_list = random.choices(all_names_list,k=nums) #取出一定數量的姓名
    return names_list

nums_int = int(input("請輸入學生數:"))
#取得nums_int個姓名
names_list = get_names(nums_int)
students = []
for i in range(nums_int):
    scores = get_score()
    new_list = [names_list[i]] + scores
    students.append(new_list)
students

ValueError: invalid literal for int() with base 10: ''

In [ ]:
import pandas as pd

students_df = pd.DataFrame(students,columns=['姓名','國文','英文','數學','地理','歷史'],index=range(1,nums_int+1))
students_df

In [3]:
students_df.head(n=8)

    姓名  國文   英文  數學  地理  歷史
1  蘇凡菁  57   98  57  53  97
2  謝貞妃  66  100  82  84  65
3  林向鈺  89   55  51  52  95
4  吳欣書  74   53  55  58  76
5  王孝純  58   63  68  86  97
6  羅佩樺  51   81  98  91  88
7  張雅芬  61   74  64  75  97
8  郭淑枝  74   54  58  96  93

In [4]:
students_df.tail(n=8)

     姓名  國文  英文  數學  地理  歷史
23  聶心怡  58  66  60  82  63
24  程玫靖  50  69  94  70  62
25  馬彥文  88  87  98  81  96
26  王梅劭  55  51  86  67  83
27  王良斌  80  75  85  77  60
28  林佳光  85  67  87  60  60
29  沈心利  83  65  69  56  66
30  王雅慧  70  68  98  84  73

In [5]:
students_df.index.name = '學號'
students_df.columns.name = '科目'
students_df

科目   姓名  國文   英文   數學  地理  歷史
學號
1   蘇凡菁  57   98   57  53  97
2   謝貞妃  66  100   82  84  65
3   林向鈺  89   55   51  52  95
4   吳欣書  74   53   55  58  76
5   王孝純  58   63   68  86  97
6   羅佩樺  51   81   98  91  88
7   張雅芬  61   74   64  75  97
8   郭淑枝  74   54   58  96  93
9   黃佩玲  63   76   67  65  71
10  唐雪豪  88   79  100  97  54
11  黃詩妃  51   57   97  70  96
12  姜琬婷  75   69   88  55  77
13  盧必妍  57   54   54  66  62
14  李蓉瑞  88   94   61  64  88
15  林詠斌  50   80   62  51  59
16  陳俊憲  93   87   86  64  53
17  劉雯芬  66   82   94  86  69
18  唐雪豪  55   51   97  77  84
19  張彥博  57   54   99  87  98
20  昌嘉洋  54   88   64  73  88
21  周怡啟  94   82   65  56  56
22  孫火清  68   51   50  87  77
23  聶心怡  58   66   60  82  63
24  程玫靖  50   69   94  70  62
25  馬彥文  88   87   98  81  96
26  王梅劭  55   51   86  67  83
27  王良斌  80   75   85  77  60
28  林佳光  85   67   87  60  60
29  沈心利  83   65   69  56  66
30  王雅慧  70   68   98  84  73

In [6]:
sum_series = students_df['國文'] + students_df['英文'] + students_df['數學'] + students_df['地理'] + students_df['歷史']
sum_series

學號
1     362
2     397
3     342
4     316
5     372
6     409
7     371
8     375
9     342
10    418
11    371
12    364
13    293
14    395
15    302
16    383
17    397
18    364
19    395
20    367
21    353
22    333
23    329
24    345
25    450
26    342
27    377
28    359
29    339
30    393
dtype: int64

In [7]:
students_df['總分'] = sum_series
students_df['平均'] = sum_series / 5.0
students_df

科目   姓名  國文   英文   數學  地理  歷史   總分    平均
學號
1   蘇凡菁  57   98   57  53  97  362  72.4
2   謝貞妃  66  100   82  84  65  397  79.4
3   林向鈺  89   55   51  52  95  342  68.4
4   吳欣書  74   53   55  58  76  316  63.2
5   王孝純  58   63   68  86  97  372  74.4
6   羅佩樺  51   81   98  91  88  409  81.8
7   張雅芬  61   74   64  75  97  371  74.2
8   郭淑枝  74   54   58  96  93  375  75.0
9   黃佩玲  63   76   67  65  71  342  68.4
10  唐雪豪  88   79  100  97  54  418  83.6
11  黃詩妃  51   57   97  70  96  371  74.2
12  姜琬婷  75   69   88  55  77  364  72.8
13  盧必妍  57   54   54  66  62  293  58.6
14  李蓉瑞  88   94   61  64  88  395  79.0
15  林詠斌  50   80   62  51  59  302  60.4
16  陳俊憲  93   87   86  64  53  383  76.6
17  劉雯芬  66   82   94  86  69  397  79.4
18  唐雪豪  55   51   97  77  84  364  72.8
19  張彥博  57   54   99  87  98  395  79.0
20  昌嘉洋  54   88   64  73  88  367  73.4
21  周怡啟  94   82   65  56  56  353  70.6
22  孫火清  68   51   50  87  77  333  66.6
23  聶心怡  58   66   60  82  63  329  65.8
24  程玫靖  50   69   94  70  62  345  69.0
25  馬彥文  88   87   98  81  96  450  90.0
26  王梅劭  55   51   86  67  83  342  68.4
27  王良斌  80   75   85  77  60  377  75.4
28  林佳光  85   67   87  60  60  359  71.8
29  沈心利  83   65   69  56  66  339  67.8
30  王雅慧  70   68   98  84  73  393  78.6

In [8]:
students_df.to_csv('學生成績.csv')