In [1]:
import numpy as np
import pandas as pd

frame = pd.read_excel('學生成績單.xlsx')
frame

    學號   姓名  國文   英文   數學  地理  歷史   總分    平均  排名
0   25  馬彥文  88   87   98  81  96  450  90.0   1
1   10  唐雪豪  88   79  100  97  54  418  83.6   2
2    6  羅佩樺  51   81   98  91  88  409  81.8   3
3   17  劉雯芬  66   82   94  86  69  397  79.4   4
4    2  謝貞妃  66  100   82  84  65  397  79.4   4
5   19  張彥博  57   54   99  87  98  395  79.0   6
6   14  李蓉瑞  88   94   61  64  88  395  79.0   6
7   30  王雅慧  70   68   98  84  73  393  78.6   8
8   16  陳俊憲  93   87   86  64  53  383  76.6   9
9   27  王良斌  80   75   85  77  60  377  75.4  10
10   8  郭淑枝  74   54   58  96  93  375  75.0  11
11   5  王孝純  58   63   68  86  97  372  74.4  12
12  11  黃詩妃  51   57   97  70  96  371  74.2  13
13   7  張雅芬  61   74   64  75  97  371  74.2  13
14  20  昌嘉洋  54   88   64  73  88  367  73.4  15
15  18  唐雪豪  55   51   97  77  84  364  72.8  16
16  12  姜琬婷  75   69   88  55  77  364  72.8  16
17   1  蘇凡菁  57   98   57  53  97  362  72.4  18
18  28  林佳光  85   67   87  60  60  359  71.8  19
19  21  周怡啟  94   82   65  56  56  353  70.6  20
20  24  程玫靖  50   69   94  70  62  345  69.0  21
21   3  林向鈺  89   55   51  52  95  342  68.4  22
22  26  王梅劭  55   51   86  67  83  342  68.4  22
23   9  黃佩玲  63   76   67  65  71  342  68.4  22
24  29  沈心利  83   65   69  56  66  339  67.8  25
25  22  孫火清  68   51   50  87  77  333  66.6  26
26  23  聶心怡  58   66   60  82  63  329  65.8  27
27   4  吳欣書  74   53   55  58  76  316  63.2  28
28  15  林詠斌  50   80   62  51  59  302  60.4  29
29  13  盧必妍  57   54   54  66  62  293  58.6  30

In [2]:
students_frame = frame[["國文","英文","數學","地理","歷史"]]
students_frame

    國文   英文   數學  地理  歷史
0   88   87   98  81  96
1   88   79  100  97  54
2   51   81   98  91  88
3   66   82   94  86  69
4   66  100   82  84  65
5   57   54   99  87  98
6   88   94   61  64  88
7   70   68   98  84  73
8   93   87   86  64  53
9   80   75   85  77  60
10  74   54   58  96  93
11  58   63   68  86  97
12  51   57   97  70  96
13  61   74   64  75  97
14  54   88   64  73  88
15  55   51   97  77  84
16  75   69   88  55  77
17  57   98   57  53  97
18  85   67   87  60  60
19  94   82   65  56  56
20  50   69   94  70  62
21  89   55   51  52  95
22  55   51   86  67  83
23  63   76   67  65  71
24  83   65   69  56  66
25  68   51   50  87  77
26  58   66   60  82  63
27  74   53   55  58  76
28  50   80   62  51  59
29  57   54   54  66  62

In [3]:
#mean(),std(),max(),min(),median(),corr()
students_frame['國文'].mean()

68.6

In [4]:
students_frame.mean()

國文    68.600000
英文    71.000000
數學    76.466667
地理    72.333333
歷史    76.766667
dtype: float64

In [5]:
students_frame.mean(axis=1)

0     90.0
1     83.6
2     81.8
3     79.4
4     79.4
5     79.0
6     79.0
7     78.6
8     76.6
9     75.4
10    75.0
11    74.4
12    74.2
13    74.2
14    73.4
15    72.8
16    72.8
17    72.4
18    71.8
19    70.6
20    69.0
21    68.4
22    68.4
23    68.4
24    67.8
25    66.6
26    65.8
27    63.2
28    60.4
29    58.6
dtype: float64

In [6]:
display(students_frame['國文'])
for item in students_frame['國文']:
    if item >= 80:
        print('優')
    elif item >= 70:
        print('甲')
    elif item >= 60:
        print('乙')
    else:
        print('丙')

0     88
1     88
2     51
3     66
4     66
5     57
6     88
7     70
8     93
9     80
10    74
11    58
12    51
13    61
14    54
15    55
16    75
17    57
18    85
19    94
20    50
21    89
22    55
23    63
24    83
25    68
26    58
27    74
28    50
29    57
Name: 國文, dtype: int64

優
優
丙
乙
乙
丙
優
甲
優
優
甲
丙
丙
乙
丙
丙
甲
丙
優
優
丙
優
丙
乙
優
乙
丙
甲
丙
丙

In [7]:
def fun1(item):
    if item >= 80:
        return '優'
    elif item >= 70:
        return '甲'
    elif item >= 60:
        return '乙'
    else:
        return '丙'
    
students_frame['國文'].map(fun1)

0     優
1     優
2     丙
3     乙
4     乙
5     丙
6     優
7     甲
8     優
9     優
10    甲
11    丙
12    丙
13    乙
14    丙
15    丙
16    甲
17    丙
18    優
19    優
20    丙
21    優
22    丙
23    乙
24    優
25    乙
26    丙
27    甲
28    丙
29    丙
Name: 國文, dtype: object

In [8]:
students_frame['國文等級'] = students_frame['國文'].map(fun1)
students_frame

/tmp/ipykernel_4767/2974217727.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students_frame['國文等級'] = students_frame['國文'].map(fun1)

    國文   英文   數學  地理  歷史 國文等級
0   88   87   98  81  96    優
1   88   79  100  97  54    優
2   51   81   98  91  88    丙
3   66   82   94  86  69    乙
4   66  100   82  84  65    乙
5   57   54   99  87  98    丙
6   88   94   61  64  88    優
7   70   68   98  84  73    甲
8   93   87   86  64  53    優
9   80   75   85  77  60    優
10  74   54   58  96  93    甲
11  58   63   68  86  97    丙
12  51   57   97  70  96    丙
13  61   74   64  75  97    乙
14  54   88   64  73  88    丙
15  55   51   97  77  84    丙
16  75   69   88  55  77    甲
17  57   98   57  53  97    丙
18  85   67   87  60  60    優
19  94   82   65  56  56    優
20  50   69   94  70  62    丙
21  89   55   51  52  95    優
22  55   51   86  67  83    丙
23  63   76   67  65  71    乙
24  83   65   69  56  66    優
25  68   51   50  87  77    乙
26  58   66   60  82  63    丙
27  74   53   55  58  76    甲
28  50   80   62  51  59    丙
29  57   54   54  66  62    丙

In [9]:
students_frame = frame[["國文","英文","數學","地理","歷史"]]
students_frame

    國文   英文   數學  地理  歷史
0   88   87   98  81  96
1   88   79  100  97  54
2   51   81   98  91  88
3   66   82   94  86  69
4   66  100   82  84  65
5   57   54   99  87  98
6   88   94   61  64  88
7   70   68   98  84  73
8   93   87   86  64  53
9   80   75   85  77  60
10  74   54   58  96  93
11  58   63   68  86  97
12  51   57   97  70  96
13  61   74   64  75  97
14  54   88   64  73  88
15  55   51   97  77  84
16  75   69   88  55  77
17  57   98   57  53  97
18  85   67   87  60  60
19  94   82   65  56  56
20  50   69   94  70  62
21  89   55   51  52  95
22  55   51   86  67  83
23  63   76   67  65  71
24  83   65   69  56  66
25  68   51   50  87  77
26  58   66   60  82  63
27  74   53   55  58  76
28  50   80   62  51  59
29  57   54   54  66  62

In [10]:
def fun1(item):
    if item >= 80:
        return '優'
    elif item >= 70:
        return '甲'
    elif item >= 60:
        return '乙'
    else:
        return '丙'
students_frame.map(fun1)

   國文 英文 數學 地理 歷史
0   優  優  優  優  優
1   優  甲  優  優  丙
2   丙  優  優  優  優
3   乙  優  優  優  乙
4   乙  優  優  優  乙
5   丙  丙  優  優  優
6   優  優  乙  乙  優
7   甲  乙  優  優  甲
8   優  優  優  乙  丙
9   優  甲  優  甲  乙
10  甲  丙  丙  優  優
11  丙  乙  乙  優  優
12  丙  丙  優  甲  優
13  乙  甲  乙  甲  優
14  丙  優  乙  甲  優
15  丙  丙  優  甲  優
16  甲  乙  優  丙  甲
17  丙  優  丙  丙  優
18  優  乙  優  乙  乙
19  優  優  乙  丙  丙
20  丙  乙  優  甲  乙
21  優  丙  丙  丙  優
22  丙  丙  優  乙  優
23  乙  甲  乙  乙  甲
24  優  乙  乙  丙  乙
25  乙  丙  丙  優  甲
26  丙  乙  乙  優  乙
27  甲  丙  丙  丙  甲
28  丙  優  乙  丙  丙
29  丙  丙  丙  乙  乙

In [11]:
students_frame

    國文   英文   數學  地理  歷史
0   88   87   98  81  96
1   88   79  100  97  54
2   51   81   98  91  88
3   66   82   94  86  69
4   66  100   82  84  65
5   57   54   99  87  98
6   88   94   61  64  88
7   70   68   98  84  73
8   93   87   86  64  53
9   80   75   85  77  60
10  74   54   58  96  93
11  58   63   68  86  97
12  51   57   97  70  96
13  61   74   64  75  97
14  54   88   64  73  88
15  55   51   97  77  84
16  75   69   88  55  77
17  57   98   57  53  97
18  85   67   87  60  60
19  94   82   65  56  56
20  50   69   94  70  62
21  89   55   51  52  95
22  55   51   86  67  83
23  63   76   67  65  71
24  83   65   69  56  66
25  68   51   50  87  77
26  58   66   60  82  63
27  74   53   55  58  76
28  50   80   62  51  59
29  57   54   54  66  62

In [12]:
def fun2(s):
    return s.min()

students_frame.apply(fun2)

國文    50
英文    51
數學    50
地理    51
歷史    53
dtype: int64

In [13]:
def fun3(s):
    return s[s < 60].count()
students_frame.apply(fun3,axis=1)

0     0
1     1
2     1
3     0
4     0
5     2
6     0
7     0
8     1
9     0
10    2
11    1
12    2
13    0
14    1
15    2
16    1
17    3
18    0
19    2
20    1
21    3
22    2
23    0
24    1
25    2
26    1
27    3
28    3
29    3
dtype: int64

In [14]:
students_frame['不及科目數量'] = students_frame.apply(fun3,axis=1)
students_frame

/tmp/ipykernel_4767/718534511.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students_frame['不及科目數量'] = students_frame.apply(fun3,axis=1)

    國文   英文   數學  地理  歷史  不及科目數量
0   88   87   98  81  96       0
1   88   79  100  97  54       1
2   51   81   98  91  88       1
3   66   82   94  86  69       0
4   66  100   82  84  65       0
5   57   54   99  87  98       2
6   88   94   61  64  88       0
7   70   68   98  84  73       0
8   93   87   86  64  53       1
9   80   75   85  77  60       0
10  74   54   58  96  93       2
11  58   63   68  86  97       1
12  51   57   97  70  96       2
13  61   74   64  75  97       0
14  54   88   64  73  88       1
15  55   51   97  77  84       2
16  75   69   88  55  77       1
17  57   98   57  53  97       3
18  85   67   87  60  60       0
19  94   82   65  56  56       2
20  50   69   94  70  62       1
21  89   55   51  52  95       3
22  55   51   86  67  83       2
23  63   76   67  65  71       0
24  83   65   69  56  66       1
25  68   51   50  87  77       2
26  58   66   60  82  63       1
27  74   53   55  58  76       3
28  50   80   62  51  59       3
29  57   54   54  66  62       3

In [16]:
students_frame = frame[["國文","英文","數學","地理","歷史"]]
students_frame

    國文   英文   數學  地理  歷史
0   88   87   98  81  96
1   88   79  100  97  54
2   51   81   98  91  88
3   66   82   94  86  69
4   66  100   82  84  65
5   57   54   99  87  98
6   88   94   61  64  88
7   70   68   98  84  73
8   93   87   86  64  53
9   80   75   85  77  60
10  74   54   58  96  93
11  58   63   68  86  97
12  51   57   97  70  96
13  61   74   64  75  97
14  54   88   64  73  88
15  55   51   97  77  84
16  75   69   88  55  77
17  57   98   57  53  97
18  85   67   87  60  60
19  94   82   65  56  56
20  50   69   94  70  62
21  89   55   51  52  95
22  55   51   86  67  83
23  63   76   67  65  71
24  83   65   69  56  66
25  68   51   50  87  77
26  58   66   60  82  63
27  74   53   55  58  76
28  50   80   62  51  59
29  57   54   54  66  62

In [17]:
def fun5(s):
    return pd.Series([s.max(),s.min(),s.median(),s.mean(),s.std()],
                     index=["最高分","最低分","中間值","平均","標準差"])
students_frame.apply(fun5)

            國文          英文          數學         地理         歷史
最高分  94.000000  100.000000  100.000000  97.000000  98.000000
最低分  50.000000   51.000000   50.000000  51.000000  53.000000
中間值  66.000000   69.000000   75.500000  71.500000  76.500000
平均   68.600000   71.000000   76.466667  72.333333  76.766667
標準差  14.526076   14.899664   17.472606  13.794885  15.386253